# Generated by Django 4.0.1 on 2022-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='factor',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
