# Generated by Django 4.0.1 on 2022-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebapp', '0003_conversiones_delete_conversion_delete_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiones',
            name='tasa',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='conversiones',
            name='monto_clp',
            field=models.IntegerField(),
        ),
    ]
